---
# Credentials for SSH-Connection
username: INSERT_SERVER_USERNAME_HERE
hostname: INSERT_SERVER_HOSTNAME_HERE
port: INSERT_SERVER_PORT_HERE
private-key-file: INSERT_PATH_TO_RSA_PRIVATE_KEY_HERE
password: INSERT_SERVER_PASSWORD_HERE
# Spotify app credentials
app-id: INSERT_APP_ID_HERE
app-secret: INSERT_APP_SECRET_HERE
redirect-uri: INSERT_REDIRECT_URI_HERE
# Server config
server-path-to-groups: INSERT_SERVER_PATH_TO_GROUP_FOLDER_HERE
smergify-script: start_smergify.sh
