---
# Spotify app credentials
app-id: INSERT_SPOTIFY_APP_ID_HERE
app-secret: INSERT_SPOTIFY_APP_SECRET_HERE
redirect-uri: INSERT_REDIRECT_URI_HERE
# Files
database-name: INSERT_DATABASE_NAME_HERE
log-file-name: INSERT_LOG_FILE_NAME_HERE
# Configuration
minimum-playlist-size: INSERT_THE_MINIMUM_AMOUNT_OF_SONGS_IN_PLAYLIST_HERE
target-playlist-size: INSERT_THE_DESIRED_AMOUNT_OF_SONGS_IN_PLAYLIST_HERE
days-to-update-users-after: INSERT_NUMBER_OF_DAYS_AFTER_WHICH_USER_GETS_UPDATED_HERE
