---
app-id: INSERT_SPOTIFY_APP_ID_HERE
app-secret: INSERT_SPOTIFY_APP_SECRET_HERE
redirect-uri: INSERT_REDIRECT_URI_HERE
database-name: INSERT_DATABASE_NAME_HERE
log-file-name: INSERT_LOG_FILE_NAME_HERE
minimum-playlist-size: INSERT_THE_MINIMUM_AMOUNT_OF_SONGS_IN_PLAYLIST_HERE
maximum-playlist-size: INSERT_THE_MAXIMUM_AMOUNT_OF_SONGS_IN_PLAYLIST_HERE
