app-id: 92635772b4014626ac2cb7c44097c5c7
app-secret: 733d71e65f2a4d538f20fa647e801b6e
redirect-uri: https://binary-kitchen.eu/smergify/
database-name: data.db
log-file-name: info.log
minimum-playlist-size: 15
target-playlist-size: 50